spring:
  application:
    name: sidra-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/sidra_db
    username: ${DB_USERNAME:sidra_user}
    password: ${DB_PASSWORD:sidra_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

# Configuration JWT
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 heures en millisecondes

# Configuration OTP
otp:
  expiration: 300000 # 5 minutes en millisecondes
  max-attempts: 3
  block-duration: 300000 # 5 minutes de blocage

# Configuration SMS (à adapter selon votre fournisseur)
sms:
  api:
    url: ${SMS_API_URL:https://api.your-sms-provider.com/send}
    key: ${SMS_API_KEY:your-sms-api-key}
    sender: ${SMS_SENDER:SIDRA}

logging:
  level:
    tn.gov.ms.sidra: DEBUG
    org.springframework.security: DEBUG